baseURL = "https://dev.portalsindex.xyz/"
languageCode = "en-us"
title = "Questions Archive"
theme="archie"
copyright = "© dev.portalsindex.xyz"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
googleAnalytics = "UA-107705235-4"
[params]
  mode="auto"
  useCDN=false
  subtitle = "Archive For Questions And Answers"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/crfdiab/arc"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://github.com/muhmd_diab/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 6
    startLevel = 2